# Generated by Django 5.1.6 on 2025-02-17 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first_model',
            name='date_time',
        ),
        migrations.AddField(
            model_name='first_model',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
